# Generated by Django 3.0 on 2019-12-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_blog', models.CharField(default='', max_length=255)),
                ('judul_blog', models.CharField(default='', max_length=255)),
                ('berita', models.TextField(default='')),
                ('tanggal', models.DateField(verbose_name='tanggal')),
            ],
        ),
        migrations.CreateModel(
            name='mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_mentee', models.CharField(default='', max_length=255)),
                ('nama_mentee', models.CharField(default='', max_length=255)),
                ('pesan_mentee', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_mentor', models.CharField(default='', max_length=255)),
                ('nama_mentor', models.CharField(default='', max_length=255)),
                ('pesan_mentor', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
