# Generated by Django 3.0 on 2019-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='jabatan_mentor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
